chessboards: "/home/hamid/Documents/phd/footefield/footefield/calibration/artifacts/chessboards_depth.yml"
output_dir: "artifacts/extrinsic_depth.yml"
cameras:
  - "cam1_5"
  - "cam1_4"
  - "cam3_4"
  - "cam3_5"
  - "cam2_4"
