chessboards: "/home/hamid/Documents/phd/footefield/footefield_feature_video/calibration/artifacts/chessboards_rgb.yml"
output_dir: "artifacts/extrinsic_rgb.yml"
cameras:
  - "cam0"
  - "cam1"
  - "cam2"
  - "cam3"
  - "cam4"
  - "cam5"
