parallel: True
display: False
output_dir: 'artifacts/chessboards_rgb.yml'
calibration_folders:
    cam0:
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0.mp4"
      offset: 0
    cam1:
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1.mp4"
      offset: 1
    cam2: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2.mp4"
      offset: 1
    cam3: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3.mp4"
      offset: 1
    cam4: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4.mp4"
      offset: 1
    cam5: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5.mp4"
      offset: 1
