chessboards_rgb: "/home/hamid/Documents/phd/footefield/footefield/calibration/artifacts/chessboards_rgb.yml"
chessboards_depth: "/home/hamid/Documents/phd/footefield/footefield/calibration/artifacts/chessboards_depth.yml"
output_dir: "artifacts/extrinsic_rgb_depth.yml"
cameras:
  - "cam1_5"
  - "cam1_4"
  - "cam3_4"
  - "cam3_5"
  - "cam2_4"