intrinsics: "/home/hamid/Documents/phd/footefield/footefield/calibration/artifacts/intrinsic_depth.yml"
calibration_folders:
    - camera_name: "cam2_4"
      path: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/azure_kinect2_4_calib_snap"
    - camera_name: "cam3_4"
      path: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/azure_kinect3_4_calib_snap"
    - camera_name: "cam3_5"
      path: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/azure_kinect3_5_calib_snap"
    - camera_name: "cam1_4"
      path: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/azure_kinect1_4_calib_snap"
    - camera_name: "cam1_5"
      path: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/azure_kinect1_5_calib_snap"