chessboards: "./artifacts/chessboards_rgb.yml"
output_dir: videos/chessboard/a1/
fps: 5
size:
  - 1920
  - 1080
calibration_folders:
    cam0:
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_0.mp4"
      offset: 0
    cam1:
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_1.mp4"
      offset: 1
    cam2: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_2.mp4"
      offset: 1
    cam3: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_3.mp4"
      offset: 1
    cam4: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_4.mp4"
      offset: 1
    cam5: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_5.mp4"
      offset: 1