model: "rtmw-x_8xb320-270e_cocktail14-384x288"
output: "artifacts/detected_skeletons_wb_a1.yml"
intrinsics: "../calibration/artifacts/intrinsic_rgb.yml"
detect_threshold: .2
track_threshold: .5
detect_min_height: 100
detect_min_x: 0
detect_max_x: 1920
visualize: True
confidence_coeff: 10
experiment_length: 150
videos:
    cam0:
      path: "../captures/cam_1.mp4"
      offset: 850
    cam1:
      path: "../captures/cam_2.mp4"
      offset: 852
    cam2: 
      path: "../captures/cam_3.mp4"
      offset: 851
    cam3: 
      path: "../captures/cam_4.mp4"
      offset: 852
    cam4: 
      path: "../captures/cam_5.mp4"
      offset: 852
    cam5: 
      path: "../captures/cam_6.mp4"
      offset: 852