skeletons_2d: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/detected_skeletons_wb.yml"
skeletons_3d: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/3d_skeletons_wb.yml"
params: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/params_global_wb.yml"
calib_param_size: 12
conf_threshold: .5
conf_power: 1
output_skeleton_3d: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/3d_skeletons_ba_wb.yml"
output_params: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/params_global_ba_wb.yml"
visualize: false