skeletons_2d: "./artifacts/detected_skeletons_wb_a1.yml"
skeletons_3d: "./artifacts/3d_skeletons_a1_wb.yml"
params: "./artifacts/params_global_a1_wb.yml"
calib_param_size: 12
conf_threshold: .4
conf_power: 1
visualize: True
output_skeleton_3d: "./artifacts/3d_skeletons_a1_wb_ba.yml"
output_params: "./artifacts/params_global_a1_wb_ba.yml"