model: "rtmpose-x_8xb256-700e_body8-halpe26-384x288"
output: "artifacts/detected_skeletons_a1.yml"
intrinsics: "../calibration/artifacts/intrinsic_rgb.yml"
visualize: True
confidence_coeff: 1
experiment_length: 1500
calibration_folders:
    cam0:
      path: "../adjust/adjusted/aug23_e1_1/cam0/0.mp4"
      offset: 0
    cam1:
      path: "../adjust/adjusted/aug23_e1_1/cam1/0.mp4"
      offset: 0
    cam2: 
      path: "../adjust/adjusted/aug23_e1_1/cam2/0.mp4"
      offset: 0
    cam3: 
      path: "../adjust/adjusted/aug23_e1_1/cam3/0.mp4"
      offset: 0
    cam4: 
      path: "../adjust/adjusted/aug23_e1_1/cam4/0.mp4"
      offset: 0
    cam5: 
      path: "../adjust/adjusted/aug23_e1_1/cam5/0.mp4"
      offset: 0
