skeletons: "artifacts/detected_skeletons_wb_a1_smooth.yml"
intrinsics: "/home/hamid/Documents/phd/footefield/footefield/calibration/artifacts/intrinsic_rgb.yml"
extrinsics: "/home/hamid/Documents/phd/footefield/footefield/calibration/artifacts/extrinsic_rgb.yml"
threshold: .6
output: "artifacts/3d_skeletons_a1_wb.yml"