skeletons: "artifacts/detected_skeletons_a1.yml"
intrinsics: "../calibration/artifacts/intrinsic_rgb.yml"
extrinsics: "../calibration/artifacts/extrinsic_rgb.yml"
threshold: .5
output: "artifacts/3d_skeletons_a1.yml"
output_params: "artifacts/params_global_a1.yml"