model: "rtmw-x_8xb320-270e_cocktail14-384x288"
confidence_coeff: 1
detect_max_x: 1620
detect_min_height: 300
detect_min_x: 300
detect_threshold: 0.5
intrinsics: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_calib_0/artifacts/intrinsic_rgb.yml
output: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/detected_skeletons_wb.yml
track_threshold: 0.6
videos:
  cam0:
    path: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam0/37.mp4
  cam1:
    path: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam1/37.mp4
  cam2:
    path: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam2/37.mp4
  cam3:
    path: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam3/37.mp4
  cam4:
    path: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam4/37.mp4
  cam5:
    path: /home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam5/37.mp4
visualize: true
