skeletons_2d: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/detected_skeletons_wb_a1_smooth.yml"
skeletons_3d: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/3d_skeletons_a1_wb_smooth.yml"
params: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/params_global_a1.yml"
calib_param_size: 12
conf_threshold: .6
conf_power: 4
output_skeleton_3d: "artifacts/3d_skeletons_a1_wb_ba.yml"
output_params: "artifacts/params_global_a1_wb_ba.yml"