skeletons_2d: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/detected_skeletons_a1_smooth.yml"
skeletons_3d: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/3d_skeletons_a1_smooth.yml"
params: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/params_global_a1.yml"
calibration_parameters_size: 21