skeletons: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/0/3d_skeletons_ba_wb.yml"
params: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/0/params_global_ba_wb.yml"
output_dir: "videos/visualizer_skeleton_3d_wb_ba/"
fps: 5
size:
  - 1920
  - 1080
calibration_folders:
    cam0:
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam0/0.mp4"
      offset: 0
    cam1:
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam1/0.mp4"
      offset: 0
    cam2: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam2/0.mp4"
      offset: 0
    cam3: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam3/0.mp4"
      offset: 0
    cam4: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam4/0.mp4"
      offset: 0
    cam5: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/segments/cam5/0.mp4"
      offset: 0
