skeletons: "artifacts/detected_skeletons_wb_a1.yml"
intrinsics: "../calibration/artifacts/intrinsic_rgb.yml"
output_dir: "videos/visualizer_skeleton_2d_wb/a1/"
fps: 5
size:
  - 1920
  - 1080
calibration_folders:
    cam0:
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0_cut.mp4"
      offset: 0
    cam1:
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1_cut.mp4"
      offset: 0
    cam2: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2_cut.mp4"
      offset: 0
    cam3: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3_cut.mp4"
      offset: 0
    cam4: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4_cut.mp4"
      offset: 0
    cam5: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5_cut.mp4"
      offset: 0
