skeletons: "artifacts/3d_skeletons_a1_ba.yml"
params: "artifacts/params_global_a1_ba.yml"
output_dir: "videos/visualizer_skeleton_3d_ba/a1/"
fps: 5
size:
  - 1920
  - 1080
calibration_folders:
    cam0:
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_0.mp4"
      offset: 300
    cam1:
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_1.mp4"
      offset: 301
    cam2: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_2.mp4"
      offset: 301
    cam3: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_3.mp4"
      offset: 301
    cam4: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_4.mp4"
      offset: 301
    cam5: 
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_5.mp4"
      offset: 301
