skeletons: "artifacts/detected_skeletons_a1.yml"
intrinsics: "../calibration/artifacts/intrinsic_rgb.yml"
output_dir: "videos/visualizer_skeleton_2d/a1/"
fps: 5
size:
  - 1920
  - 1080
calibration_folders:
    - camera_name: "cam0"
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_0.mp4"
    - camera_name: "cam1"
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_1.mp4"
    - camera_name: "cam2"
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_2.mp4"
    - camera_name: "cam3"
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_3.mp4"
    - camera_name: "cam4"
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_4.mp4"
    - camera_name: "cam5"
      path: "/home/hamid/Documents/phd/footefield/data/mocapaug21/cam_5.mp4"
