skeletons: "artifacts/detected_skeletons_a1.yml"
intrinsics: "../calibration/artifacts/intrinsic_rgb.yml"
output_dir: "videos/visualizer_skeleton_2d/a1/"
fps: 5
size:
  - 1920
  - 1080
calibration_folders:
    - camera_name: "cam0"
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0_cut.mp4"
    - camera_name: "cam1"
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1_cut.mp4"
    - camera_name: "cam2"
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2_cut.mp4"
    - camera_name: "cam3"
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3_cut.mp4"
    - camera_name: "cam4"
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4_cut.mp4"
    - camera_name: "cam5"
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5_cut.mp4"
