segment_size: 50
calib_data_dir: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_calib_0/artifacts"
output_dir: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0_wb"
videos:
  - name: "cam0"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/0/output_1.mp4"
    start: 130
    length: 1140
  - name: "cam1"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/0/output_0.mp4"
    start: 132
    length: 1140
  - name: "cam2"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/1/output_1.mp4"
    start: 132
    length: 1140
  - name: "cam3"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/1/output_0.mp4"
    start: 132
    length: 1140
  - name: "cam4"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/2/output_0.mp4"
    start: 132
    length: 1140
  - name: "cam5"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/2/output_1.mp4"
    start: 132
    length: 1140
defaults:
  skeleton_detection: "defaults_pose_wb/skeleton_detection.yml"
  skeleton_triangulation: "defaults_pose_wb/skeleton_triangulation.yml"
  skeleton_bundle_adjustment: "defaults_pose_wb/skeleton_bundle_adjustment.yml"
  skeleton_3d_normalizer: "defaults_pose_wb/skeleton_3d_normalizer.yml"
  visualizer_skeleton_3d_video_ba: "defaults_pose_wb/visualizer_skeleton_3d_video_ba.yml"
  sh: "defaults_pose_wb/sh.yml"