segment_size: 500
calibration: True
calib_data_dir: None
output_dir: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_23/aug23_calib"
videos:
  - name: "cam0"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0.mp4"
    start: 700
    length: 500
  - name: "cam1"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1.mp4"
    start: 702
    length: 500
  - name: "cam2"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2.mp4"
    start: 702
    length: 500
  - name: "cam3"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3.mp4"
    start: 702
    length: 500
  - name: "cam4"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4.mp4"
    start: 702
    length: 500
  - name: "cam5"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5.mp4"
    start: 702
    length: 500
defaults:
  detect_chessboard_rgb: "defaults/detect_chessboard_rgb.yml"
  calc_intrinsic_rgb: "defaults/calc_intrinsic_rgb.yml"
  calc_extrinsic_rgb: "defaults/calc_extrinsic_rgb.yml"
  sh: "defaults/sh_calib.yml"