segment_size: 1030
output_dir: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_calib_1"
videos:
  - name: "cam0"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/0/output_1 (6).mp4"
    start: 265
    length: 1030
  - name: "cam1"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/0/output_0 (6).mp4"
    start: 267
    length: 1030
  - name: "cam2"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/1/output_1 (6).mp4"
    start: 267
    length: 1030
  - name: "cam3"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/1/output_0 (6).mp4"
    start: 267
    length: 1030
  - name: "cam4"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/2/output_0 (6).mp4"
    start: 267
    length: 1030
  - name: "cam5"
    path: "/home/hamid/Documents/phd/footefield/data/real aug 24/2/output_1 (6).mp4"
    start: 267
    length: 1030
defaults:
  detect_chessboard_rgb: "defaults_calib/detect_chessboard_rgb.yml"
  calc_intrinsic_rgb: "defaults_calib/calc_intrinsic_rgb.yml"
  calc_extrinsic_rgb: "defaults_calib/calc_extrinsic_rgb.yml"
  sh: "defaults_calib/sh_calib.yml"