segment_size: 50
output_dir: "adjusted/aug23_e1_2/"
videos:
  - name: "cam0"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0.mp4"
    start: 2050
    length: 950
  - name: "cam1"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1.mp4"
    start: 2052
    length: 950
  - name: "cam2"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2.mp4"
    start: 2052
    length: 950
  - name: "cam3"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3.mp4"
    start: 2052
    length: 950
  - name: "cam4"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4.mp4"
    start: 2052
    length: 950
  - name: "cam5"
    path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5.mp4"
    start: 2052
    length: 950