#!/bin/bash
ffmpeg -i "visualizer_skeleton_video_a1_azure_kinect1_5_calib_snap_org.avi" -i "visualizer_skeleton_video_a1_azure_kinect1_5_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a1_azure_kinect1_5_calib_snap_all.mp4"
ffmpeg -i "visualizer_skeleton_video_a1_azure_kinect2_4_calib_snap_org.avi" -i "visualizer_skeleton_video_a1_azure_kinect2_4_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a1_azure_kinect2_4_calib_snap_all.mp4"
ffmpeg -i "visualizer_skeleton_video_a1_azure_kinect3_4_calib_snap_org.avi" -i "visualizer_skeleton_video_a1_azure_kinect3_4_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a1_azure_kinect3_4_calib_snap_all.mp4"
ffmpeg -i "visualizer_skeleton_video_a1_azure_kinect3_5_calib_snap_org.avi" -i "visualizer_skeleton_video_a1_azure_kinect3_5_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a1_azure_kinect3_5_calib_snap_all.mp4"

ffmpeg -i "visualizer_skeleton_video_a2_azure_kinect1_5_calib_snap_org.avi" -i "visualizer_skeleton_video_a2_azure_kinect1_5_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a2_azure_kinect1_5_calib_snap_all.mp4"
ffmpeg -i "visualizer_skeleton_video_a2_azure_kinect2_4_calib_snap_org.avi" -i "visualizer_skeleton_video_a2_azure_kinect2_4_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a2_azure_kinect2_4_calib_snap_all.mp4"
ffmpeg -i "visualizer_skeleton_video_a2_azure_kinect3_4_calib_snap_org.avi" -i "visualizer_skeleton_video_a2_azure_kinect3_4_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a2_azure_kinect3_4_calib_snap_all.mp4"
ffmpeg -i "visualizer_skeleton_video_a2_azure_kinect3_5_calib_snap_org.avi" -i "visualizer_skeleton_video_a2_azure_kinect3_5_calib_snap_mesh.avi" -filter_complex "[0:v][1:v]hstack=inputs=2[outv]" -map "[outv]" -an "visualizer_skeleton_video_a2_azure_kinect3_5_calib_snap_all.mp4"