skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
params: "../pose_estimation/artifacts/params_global_a1_wb_ba.yml"
params_smplx: "artifacts/smplx_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-6
weight_distance: 1.0
weight_scale: 1.0e-10
learning_rate: 2.0e-3
scale_mask: 8
epochs: 200
output: "artifacts/smplx_opt_global_a1.yml"
videos_mask:
  cam0: "../adjust/adjusted/aug23_e1_1/cam0/0_mask.mp4"
  cam1: "../adjust/adjusted/aug23_e1_1/cam1/0_mask.mp4"
  cam2: "../adjust/adjusted/aug23_e1_1/cam2/0_mask.mp4"
  cam3: "../adjust/adjusted/aug23_e1_1/cam3/0_mask.mp4"
  cam4: "../adjust/adjusted/aug23_e1_1/cam4/0_mask.mp4"
  cam5: "../adjust/adjusted/aug23_e1_1/cam5/0_mask.mp4"