skeletons_norm: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/3d_skeletons_ba_wb_norm.yml"
gender: "neutral"
models_root: "models"
visualize: True
visualize_mesh: True
learning_rate: .02
weight_scale: 1.0e-10
epochs: 1000
output: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e1/artifacts/37/smplx_opt_alpha.yml"