skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
params: "../pose_estimation/artifacts/params_global_a1_wb_ba.yml"
params_smplx: "artifacts/smplx_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-8
weight_distance: 1.0
weight_scale: 1.0e-10
learning_rate: 2.0e-3
scale_mask: 8
epochs: 200
output: "artifacts/smplx_opt_global_a1.yml"
videos_mask:
  cam0: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0_cut_mask.mp4"
  cam1: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1_cut_mask.mp4" 
  cam2: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2_cut_mask.mp4"
  cam3: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3_cut_mask.mp4"
  cam4: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4_cut_mask.mp4"
  cam5: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5_cut_mask.mp4"