skeletons: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
params: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/params_global_a1_wb_ba.yml"
params_smplx: "artifacts/smplx_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-8
weight_distance: 1.0
learning_rate: 2.0e-3
scale_mask: 8
epochs: 100
output: "artifacts/smplx_opt_global_a1.yml"
images_mask:
  cam2_4: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/a1/azure_kinect2_4/mask"
  cam3_4: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/a1/azure_kinect3_4/mask"
  cam3_5: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/a1/azure_kinect3_5/mask"
  cam1_4: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/a1/azure_kinect1_4/mask"
  cam1_5: "/home/hamid/Documents/phd/footefield/data/AzureKinectRecord_0729/a1/azure_kinect1_5/mask"