skeletons: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/artifacts/26/3d_skeletons_ba_wb_norm.yml"
params: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/artifacts/26/params_global_ba_wb.yml"
params_smplx: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/artifacts/26/smplx_opt_alpha.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-6
weight_distance: 1.0
weight_scale: 1.0e-10
learning_rate: 2.0e-4
scale_mask: 8
epochs: 200
output: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/artifacts/26/smplx_opt_global.yml"
videos_mask:
  cam0: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/segments_mask/26/cam0.mp4"
  cam1: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/segments_mask/26/cam1.mp4"
  cam2: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/segments_mask/26/cam2.mp4"
  cam3: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/segments_mask/26/cam3.mp4"
  cam4: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/segments_mask/26/cam4.mp4"
  cam5: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e0/segments_mask/26/cam5.mp4"