skeletons: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
learning_rate: .02
epochs: 1000
output: "artifacts/smplx_opt_alpha_a1.yml"