skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
params: "../pose_estimation/artifacts/params_global_a1_wb_ba.yml"
params_smplx: "artifacts/smplx_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-6
weight_distance: 1.0
weight_scale: 1.0e-10
learning_rate: 2.0e-3
scale_mask: 8
epochs: 200
output: "artifacts/smplx_opt_global_a1.yml"
videos_mask:
  cam0:
    path: "../segmask/videos/cam_1.mp4"
    offset: 0
  cam1:
    path: "../segmask/videos/cam_2.mp4"
    offset: 0
  cam2:
    path: "../segmask/videos/cam_3.mp4"
    offset: 0
  cam3:
    path: "../segmask/videos/cam_4.mp4"
    offset: 0
  cam4:
    path: "../segmask/videos/cam_5.mp4"
    offset: 0
  cam5:
    path: "../segmask/videos/cam_6.mp4"
    offset: 0
