params_smplx: "artifacts/smplx_opt_alpha_a1.yml"
params: "../pose_estimation/artifacts/params_global_a1_wb_ba.yml"
skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_wb_ba.yml"
skeletons_norm: "../pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
gender: "neutral"
models_root: "models"
visualize_skeleton: False
visualize_joints: True
visualize_mesh: True
fps: 5
size:
  - 1920
  - 1080
output: "videos/visualizer_smplx_alpha/a1/"
calibration_folders:
    cam0:
      path: "../adjust/adjusted/aug23_e1_1/cam0/0.mp4"
      offset: 0
    cam1:
      path: "../adjust/adjusted/aug23_e1_1/cam1/0.mp4"
      offset: 0
    cam2: 
      path: "../adjust/adjusted/aug23_e1_1/cam2/0.mp4"
      offset: 0
    cam3: 
      path: "../adjust/adjusted/aug23_e1_1/cam3/0.mp4"
      offset: 0
    cam4: 
      path: "../adjust/adjusted/aug23_e1_1/cam4/0.mp4"
      offset: 0
    cam5: 
      path: "../adjust/adjusted/aug23_e1_1/cam5/0.mp4"
      offset: 0
