params_smplx: "artifacts/smplx_opt_alpha_a1.yml"
params: "../pose_estimation/artifacts/params_global_a1_wb_ba.yml"
skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_wb_ba.yml"
skeletons_norm: "../pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
gender: "neutral"
models_root: "models"
visualize_skeleton: True
visualize_joints: True
visualize_mesh: False
fps: 5
size:
  - 1920
  - 1080
output: "videos/visualizer_smplx_alpha/a1/"
calibration_folders:
    cam0:
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0_cut.mp4"
      offset: 0
    cam1:
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1_cut.mp4"
      offset: 0
    cam2: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2_cut.mp4"
      offset: 0
    cam3: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3_cut.mp4"
      offset: 0
    cam4: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4_cut.mp4"
      offset: 0
    cam5: 
      path: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5_cut.mp4"
      offset: 0
