skeletons_norm: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/3d_skeletons_a1_wb_ba_norm.yml"
visualize_poses: False
visualize_joints: True
visualize_mesh: True
params_smplx: "artifacts/smplx_opt_global_a1.yml"
gender: "neutral"
models_root: "models"
