skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_ba_norm.yml"
params: "../pose_estimation/artifacts/params_global_a1_ba.yml"
params_smpl: "artifacts/smpl_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-7
weight_distance: 1.0
learning_rate: 2.0e-3
scale_mask: 8
epochs: 200
output: "artifacts/smpl_opt_global_a1.yml"
videos_mask:
  cam0: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam0_cut_mask.mp4"
  cam1: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam1_cut_mask.mp4" 
  cam2: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam2_cut_mask.mp4"
  cam3: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam3_cut_mask.mp4"
  cam4: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam4_cut_mask.mp4"
  cam5: "/home/hamid/Documents/phd/footefield/data/Aug 23 real/cam5_cut_mask.mp4"