skeletons: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/3d_skeletons_a1_ba_norm.yml"
gender: "neutral"
models_root: "models"
visualize: False
epochs: 2000
output: "artifacts/smpl_opt_alpha_a1.yml"