skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_ba_norm.yml"
gender: "neutral"
models_root: "models"
weight_scale: 1.0e-4
visualize: False
visualize_mesh: True
learning_rate: .002
epochs: 2000
output: "artifacts/smpl_opt_alpha_a1.yml"