skeletons: "../pose_estimation/artifacts/3d_skeletons_a1_ba_norm.yml"
params: "../pose_estimation/artifacts/params_global_a1_ba.yml"
params_smpl: "artifacts/smpl_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-7
weight_distance: 1.0
learning_rate: 2.0e-3
scale_mask: 8
epochs: 200
output: "artifacts/smpl_opt_global_a1.yml"
videos_mask:
  cam0: "../adjust/adjusted/aug23_e1_1/cam0/0_mask.mp4"
  cam1: "../adjust/adjusted/aug23_e1_1/cam1/0_mask.mp4"
  cam2: "../adjust/adjusted/aug23_e1_1/cam2/0_mask.mp4"
  cam3: "../adjust/adjusted/aug23_e1_1/cam3/0_mask.mp4"
  cam4: "../adjust/adjusted/aug23_e1_1/cam4/0_mask.mp4"
  cam5: "../adjust/adjusted/aug23_e1_1/cam5/0_mask.mp4"