skeletons: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/artifacts/0/3d_skeletons_ba_norm.yml"
params: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/artifacts/0/params_global_ba.yml"
params_smpl: "artifacts/smpl_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize: False
visualize_mesh: True
visualize_chamfer_projection: False
weight_chamfer: 1.0e-7
weight_distance: 1.0
learning_rate: 2.0e-3
scale_mask: 8
epochs: 200
output: "artifacts/smpl_opt_global_a1.yml"
videos_mask:
  cam0: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam0/0_mask.mp4"
  cam1: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam1/0_mask.mp4"
  cam2: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam2/0_mask.mp4"
  cam3: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam3/0_mask.mp4"
  cam4: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam4/0_mask.mp4"
  cam5: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam5/0_mask.mp4"