params_smpl: "artifacts/smpl_opt_alpha_a1.yml"
params: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/artifacts/0/params_global_ba.yml"
skeletons: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/artifacts/0/3d_skeletons_ba.yml"
skeletons_norm: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/artifacts/0/3d_skeletons_ba_norm.yml"
gender: "neutral"
models_root: "models"
visualize_skeleton: False
visualize_joints: True
visualize_mesh: True
fps: 5
size:
  - 1920
  - 1080
output: "videos/visualizer_smpl_alpha/a1/"
calibration_folders:
    cam0:
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam0/0.mp4"
      offset: 0
    cam1:
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam1/0.mp4"
      offset: 0
    cam2: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam2/0.mp4"
      offset: 0
    cam3: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam3/0.mp4"
      offset: 0
    cam4: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam4/0.mp4"
      offset: 0
    cam5: 
      path: "/home/hamid/Documents/phd/footefield/data/dataset_mocap24/aug_24/aug24_e2_0/segments/cam5/0.mp4"
      offset: 0
