skeletons_norm: "../pose_estimation/artifacts/3d_skeletons_a1_ba_norm.yml"
params_smpl: "artifacts/smpl_opt_alpha_a1.yml"
gender: "neutral"
models_root: "models"
visualize_poses: False
visualize_joints: True
visualize_mesh: True
