skeletons_norm: "/home/hamid/Documents/phd/footefield/footefield/pose_estimation/artifacts/3d_skeletons_a1_ba_norm.yml"
params_smpl: "artifacts/smpl_opt_global_a1.yml"
gender: "neutral"
models_root: "models"
visualize_poses: True
visualize_joints: True
visualize_mesh: False
